### PR TITLE
add: search main_menu to menu_registration_api

### PR DESCRIPTION
**Pull request by ppinkypeach**
By default, the value (is_main_menu) of the main menu is **"false"**, and a function that makes the value (is_main_menu) of the main menu **"true"** through the update function in crud was created.

### CODE REVIEW

**Review by KKodiac — APPROVED** [review]
LGTM👍🏻

**Comment by sktkddn777** [comment]
영어 잘하네여 👍

**Review by kimich1218 — COMMENTED** [review]
존경합니다!

**Review by edi54 — APPROVED** [review]
I've seen over it. I really appreciate your hard work!

**Comment by juwon5272** [comment]
수고하셨어요

**Pull request merged**
