### PR TITLE
Updated: feat: add store registration

### PR DESCRIPTION
**Pull request by ppinkypeach**
## 개요
Category, location, menu, and user table were added to store_registration.

## 작업사항
 I connected all foreign key to the store table.

## 변경로직
 1) The category name's type was given ENUM without adding a category table.
 2) To save location coordinates, Coordinates class was added at models.py.
 3) To register a store, User_id, location_id and location_points should be present.

### CODE REVIEW

**Review by edi54 — APPROVED** [review]
수고하셨습니다!!

**Comment by juwon5272** [comment]
고생하셨어요

**Review by KKodiac — APPROVED** [review]
👏👏👏👏👏

**Review by sktkddn777 — APPROVED** [review]
고생하셨어요~!!

**Pull request merged**
